[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3001
  publish = "build"
  autoLaunch = true
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Настройки для автоматического деплоя
[context.production]
  environment = { NODE_VERSION = "18", NPM_FLAGS = "--legacy-peer-deps" }

[context.deploy-preview]
  environment = { NODE_VERSION = "18", NPM_FLAGS = "--legacy-peer-deps" }

# Настройки для проверки сборки
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
