[build]
  command = "npm install @rainbow-me/rainbowkit@2 wagmi@2 viem@2.x @tanstack/react-query --legacy-peer-deps && CI=false npm run build"
  publish = "build"
  functions = "netlify/functions"

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3001
  publish = "build"
  autoLaunch = true
  framework = "#custom"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Настройки для автоматического деплоя
[context.production]
  environment = { NODE_VERSION = "18", NPM_FLAGS = "--legacy-peer-deps", CI = "false" }

[context.deploy-preview]
  environment = { NODE_VERSION = "18", NPM_FLAGS = "--legacy-peer-deps", CI = "false" }

# Настройки для проверки сборки
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true

# Настройки заголовков безопасности
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
